// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGc-F8wjB46S0qFNT-m1hbg5IwPovzTHI',
    appId: '1:87606093584:web:4753fe5e70121c7d552795',
    messagingSenderId: '87606093584',
    projectId: 'vet-clinic-8f893',
    authDomain: 'vet-clinic-8f893.firebaseapp.com',
    storageBucket: 'vet-clinic-8f893.appspot.com',
    measurementId: 'G-2MVLV9GR14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXt27H55DjofrYVL3YL30sG-QI2t-3mA',
    appId: '1:87606093584:android:d19c17aa2d0bb4e7552795',
    messagingSenderId: '87606093584',
    projectId: 'vet-clinic-8f893',
    storageBucket: 'vet-clinic-8f893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_iBwow4crm1m3xb2CIYZ3M8PJbuw2IX4',
    appId: '1:87606093584:ios:09503cf115dcf1ad552795',
    messagingSenderId: '87606093584',
    projectId: 'vet-clinic-8f893',
    storageBucket: 'vet-clinic-8f893.appspot.com',
    iosClientId: '87606093584-25f82ggeiipcrm9vgift4dta6c32d6du.apps.googleusercontent.com',
    iosBundleId: 'com.example.animlaowner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_iBwow4crm1m3xb2CIYZ3M8PJbuw2IX4',
    appId: '1:87606093584:ios:1e5755d6bb41fad0552795',
    messagingSenderId: '87606093584',
    projectId: 'vet-clinic-8f893',
    storageBucket: 'vet-clinic-8f893.appspot.com',
    iosClientId: '87606093584-ija6to961gsur32coo5mrm1ic1k9faco.apps.googleusercontent.com',
    iosBundleId: 'com.example.animlaowner.RunnerTests',
  );
}
